name: Setup Anchor

runs:
  using: composite
  steps:
    - name: Setup Anchor
      uses: metadaoproject/setup-anchor@v3.1
      with:
        anchor-version: '0.30.1'
        solana-cli-version: '2.0.21'
        node-version: 22
