name: Build Templates

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ./.github/workflows/actions/install-dependencies
        with:
          version: 22

      - name: Setup Anchor
        uses: ./.github/workflows/actions/setup-anchor

      - name: Run the build for all templates
        shell: bash
        run: pnpm -r --workspace-concurrency 1 build

      - name: Check for changed files
        run: git diff --exit-code